server:
  servlet:
    context-path: /task
  
logging:
   level:
    org.springframework: ERROR
    com.triangle: ERROR
    
spring:
  devtools:
    restart:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
    - dev